# Generated by Django 4.0.4 on 2022-05-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='reading',
            name='end_page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='start_page',
            field=models.IntegerField(),
        ),
    ]
